### ISSUE TITLE
%root property is serialized when can.Map instance is shared between a component viewModel and a can.route

### ISSUE THREAD

**Issue by shcarrico** [canjs/canjs#2080]
if you create a `can.Map` instance, and supply it to a component, then to `can.route`, you will get a `%root` property serialized into your route..

I worked around by adding a define block with `serialize : false` to the aforementioned Map instance, but should this property be defaulted to `serialize : false` some way?

**Comment by justinbmeyer** [comment]
Yeah, sounds like the right thing to do. Can you give an example of this happening?  Thanks!

**Comment by shcarrico** [comment]
```javascript
var vm = can.Map.extend({});
var tpl = can.mustache("<foo/>")
var comp = can.Component.extend({ 
				tag : "foo", 
				viewModel : vm, 
				events : { 
					"inserted" : function(){ 
						console.log("through the component", this.viewModel.serialize()) 
					}
				}
				});
can.$("body").append(tpl())

var i = new vm();
i.serialize(); // returns Object {}
```

the above `console.log` will produce `through the component Object {%root: Object}` when the component is inserted.

**Comment by justinbmeyer** [comment]
@shcarrico Why was a viewModel being serialized?  It will help inform the fix.

We added `%root` to help make can-ssr able to know what ajax requests a page was making. @matthewp is working on a better way of identifying these things, making `%root` unnecessary in the future.

My first impulse is to simply take whatever `can.Map` is the view-model and overwrite it's `.serialize()` to delete the `%root` that would be returned.

It's kinda hacky, but should work automatically for most situations, and we can pull it when `%root` is removed (or deprecated) in 3.0.

**Comment by shcarrico** [comment]
What I have done is to add a `define` block and set serialize to false. This seems to work OK, although I didn't know what the purpose of %root was so was concerned about side effects.

I am sharing a map instance between a "root" component and `can.route` via `can.route.map`. The idea being to have that set of properties be the base scope for the application, with the "state" living primarily in window.history

**Comment by justinbmeyer** [comment]
```js
var oldSerialize = viewModel.serialize;
viewModel.serialize = function(){
	var result = oldSerialize.apply(this, arguments);
	delete result["%root"];
	return result;
}
```

**Comment by prashantsharmain** [comment]
@justinbmeyer I added the following test to component_test.js:

		test("%root property should not be serialized inside prototype of can.Component constructor (#2080)", function () {
			var viewModel = can.Map.extend({});

			var comp = can.Component.extend({
				tag: "foo",
				viewModel: viewModel,
				events: {
					"inserted": function () {
						ok(!this.viewModel.serialize()['%root'], "serialized viewModel contains '%root' property");
					}
				}
			});

			var template = can.mustache("<foo/>");

			can.append(this.$fixture, template());
		});

I then added the following to \canjs\map\define\define.js (lines 358-359) to make this test pass:

delete serialized['%root'];
return serialized;

The test passes with this fix, but I also get the following failure:

Tests completed in 333942 milliseconds.
374 assertions of 375 passed, 1 failed.
can/component vdom: %root property should not be serialized inside prototype of can.Component constructor (#2080) (1, 0, 1)Rerun37806 ms
Died on test #1     at makeTest (http://localhost:8000/component/component_test.js:1534:3)
    at http://localhost:8000/component/component_test.js:1559:3
    at stealInstantiateResult.execute (http://localhost:8000/node_modules/steal/steal.js:5806:32)
    at linkDynamicModule (http://localhost:8000/node_modules/steal/steal.js:3547:32)
    at link (http://localhost:8000/node_modules/steal/steal.js:3407:11)
    at Object.execute (http://localhost:8000/node_modules/steal/steal.js:3726:11)
    at doDynamicExecute (http://localhost:8000/node_modules/steal/steal.js:1949:25)
    at link (http://localhost:8000/node_modules/steal/steal.js:1997:24): Cannot set property previousSibling of #<Node> which has only a getter
Source:	
TypeError: Cannot set property previousSibling of #<Node> which has only a getter
    at insertFragment (http://localhost:8000/node_modules/can-simple-dom/lib/simple-dom/document/node.js!eval:28:32)
    at DocumentFragment.Node.appendChild (http://localhost:8000/node_modules/can-simple-dom/lib/simple-dom/document/node.js!eval:82:11)
    at Function.jQuery.extend.buildFragment (http://localhost:8000/node_modules/jquery/dist/jquery.js:5672:23)
    at jQuery.fn.extend.domManip (http://localhost:8000/node_modules/jquery/dist/jquery.js:5939:22)
    at $.fn.domManip (http://localhost:8000/util/jquery/jquery.js:165:23)
    at jQuery.fn.extend.append (http://localhost:8000/node_modules/jquery/dist/jquery.js:5758:15)
    at Object.can.(anonymous function) [as append] (http://localhost:8000/util/jquery/jquery.js:123:25)
    at Object.<anonymous> (http://localhost:8000/component/component_test.js:1551:8)
    at Object.Test.run (http://localhost:8000/node_modules/steal-qunit/qunit.js:1303:18)
    at http://localhost:8000/node_modules/steal-qunit/qunit.js:1463:10

I'm not sure why can/componet dom test passed, but can/compoment vdom test fails. Any clues? Does it have anything to do with the following call:

can.append(this.$fixture, template());

**Comment by justinbmeyer** [comment]
@prashantsharmain Please make the test work with `can.stache` does it work then?

**Comment by prashantsharmain** [comment]
@justinbmeyer It does work with can.stache. Is this fix acceptable? Please note that the example that @shcarrico had shared uses can.mustache.
