### ISSUE TITLE
Result JSBin in TodoMVC Guide is broken

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2905]
[This JSBin](http://jsbin.com/labajog/1/edit?html,css,js,output) (which is shown [here](http://canjs.com/doc/guides/todomvc.html#Result)) is not working.

Here is the error:

```
Uncaught TypeError: compareOrder is not a function
runner-3.40.2.min.js:1 error TypeError: compareOrder is not a function
    at https://unpkg.com/can@3.2.2/dist/global/can.all.js:8049:28
    at Array.sort (native)
    at Object.subsetData (https://unpkg.com/can@3.2.2/dist/global/can.all.js:8048:31)
```

**Comment by justinbmeyer** [comment]
Does it work in older releases?

**Comment by phillipskevin** [comment]
After clearing localStorage this works fine.

Here is what it had before in case someone thinks this is an issue:
```json
{
  "todoCache-sets": "[{\"sort\":\"name\"}]",
  "todoCache/instance/5": "{\"name\":\"mow lawn\",\"complete\":false,\"id\":5}",
  "todoCache/instance/6": "{\"name\":\"dishes\",\"complete\":true,\"id\":6}",
  "todoCache/instance/7": "{\"name\":\"learn canjs\",\"complete\":false,\"id\":7}",
  "todoCache/set/{\"sort\":\"name\"}": "[6,7,5]"
}
```

**Comment by matthewp** [comment]
It's a bug somewhere, not sure where
