### ISSUE TITLE
production test script failing locally

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2937]
If you run:

```
npm run testee-production
```

This task fails because testee times out.  This happened for both @matthewp and myself.

Here's the debug output:

```
> DEBUG=testee:* testee test/production.html --browsers firefox

  testee:main running test for [ 'test/production.html' ] [ 'firefox' ] { browsers: 'firefox' } +0ms
  testee:main bootstrapping Testee +10ms
  testee:main starting Testee server { browsers: 'firefox',
  port: 3996,
  root: '/Users/justin/dev/canjs',
  reporter: 'Dot',
  adapter: '/testee/',
  timeout: 120,
  delay: 1000,
  tunnel: { type: 'local', port: 3996 },
  launch: { type: 'local' } } +2ms
  testee:server initializing Feathers API +1ms
  testee:hosting intializing static file server /Users/justin/dev/canjs +25ms
  testee:main testee server started and listening +10ms
  testee:main hooking up services to Mocha reporter +0ms
  testee:reporter setting up Mocha command line reporter +0ms
  testee:reporter start +1ms

  testee:main starting up localhost tunnel { type: 'local', port: 3996 } +0ms
  testee:main localhost tunnel started on http://localhost:3996 +1ms
  testee:main using browser launcher local { type: 'local' } +0ms
  testee:main browser launcher initialized +1ms
  testee:main setting up test runner +0ms
  testee:main server bootstrapped, running tests. +0ms
  testee:runner running tests for [ 'test/production.html' ] [ 'firefox' ] +0ms
  testee:runner initializing sequential test runs for browser firefox +1ms
  testee:runner running individual test http://localhost:3996/test/production.html?__token=q6o519 { browser: 'firefox' } +2ms
  testee:runner browser instance started { browser: 'firefox' } +36ms
  testee:runner tracking test run http://localhost:3996/test/production.html?__token=q6o519 { browser: 'firefox' } +0ms
  testee:html-injector injecting scripts into file /test/production.html?__token=q6o519 +1s
  testee:html-injector injecting scripts into file /node_modules/es6-promise/dist/es6-promise.js +70ms
  testee:html-injector injecting scripts into file /docs/can-guides/experiment/todomvc/bg.png +122ms
  testee:html-injector injecting scripts into file /node_modules/es6-promise/dist/es6-promise.js +1ms
  testee:html-injector injecting scripts into file /favicon.ico +1s
  testee:html-injector injecting scripts into file /dist/node_modules/can-view-import/test/hello.js +45s
  testee:html-injector injecting scripts into file /test/fixtures/foo.json +4s
  testee:runner test http://localhost:3996/test/production.html?__token=q6o519 timed out +1m
  testee:runner stopping browser instance { browser: 'firefox' } +2ms
  testee:reporter adding error to reporter { [Error: Browser timed out within 120 seconds]
  message: 'Browser timed out within 120 seconds',
  stack: 'Error: Browser timed out within 120 seconds\n    at Timeout.testTimedOut [as _onTimeout] (/Users/justin/dev/canjs/node_modules/testee/lib/runner.js:43:42)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)',
  title: 'http://localhost:3996/test/production.html?__token=q6o519 on {"browser":"firefox"}' } +441ms
  testee:main shutting down reporter +0ms
  testee:reporter end +1ms
  testee:reporter reportErrors 1 +0ms
  testee:reporter starting run { id: 'de585aa3-52c4-4cba-bee7-d5ff03795697',
  title: 'General error' } +0ms
  testee:reporter reporting error { [Error: Browser timed out within 120 seconds]
  message: 'Browser timed out within 120 seconds',
  stack: 'Error: Browser timed out within 120 seconds\n    at Timeout.testTimedOut [as _onTimeout] (/Users/justin/dev/canjs/node_modules/testee/lib/runner.js:43:42)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)',
  title: 'http://localhost:3996/test/production.html?__token=q6o519 on {"browser":"firefox"}' } +1ms
  testee:reporter starting test { id: '58e4f30a-b558-4b9e-b462-b975e5780229',
  parent: 'de585aa3-52c4-4cba-bee7-d5ff03795697',
  status: 'failed',
  err: 
   { [Error: Browser timed out within 120 seconds]
     message: 'Browser timed out within 120 seconds',
     stack: 'Error: Browser timed out within 120 seconds\n    at Timeout.testTimedOut [as _onTimeout] (/Users/justin/dev/canjs/node_modules/testee/lib/runner.js:43:42)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)',
     title: 'http://localhost:3996/test/production.html?__token=q6o519 on {"browser":"firefox"}' },
  title: 'http://localhost:3996/test/production.html?__token=q6o519 on {"browser":"firefox"}' } +0ms
  testee:reporter updating test { id: '58e4f30a-b558-4b9e-b462-b975e5780229',
  parent: 'de585aa3-52c4-4cba-bee7-d5ff03795697',
  status: 'failed',
  err: 
   { [Error: Browser timed out within 120 seconds]
     message: 'Browser timed out within 120 seconds',
     stack: 'Error: Browser timed out within 120 seconds\n    at Timeout.testTimedOut [as _onTimeout] (/Users/justin/dev/canjs/node_modules/testee/lib/runner.js:43:42)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)',
     title: 'http://localhost:3996/test/production.html?__token=q6o519 on {"browser":"firefox"}' },
  title: 'http://localhost:3996/test/production.html?__token=q6o519 on {"browser":"firefox"}' } +1ms

  !  testee:reporter updating run { status: 'finished',
  id: 'de585aa3-52c4-4cba-bee7-d5ff03795697',
  title: 'General error' } +1ms


  0 passing (2m)
  1 failing

  1) General error http://localhost:3996/test/production.html?__token=q6o519 on {"browser":"firefox"}:
     Error: Browser timed out within 120 seconds
      at Timeout.testTimedOut [as _onTimeout] (/Users/justin/dev/canjs/node_modules/testee/lib/runner.js:43:42)
      at tryOnTimeout (timers.js:224:11)
      at Timer.listOnTimeout (timers.js:198:5)

```

Locally I'm running FF `50.0.1`.  But I am pretty sure it was breaking earlier today with a `49` version.

@daffl / @phillipskevin any thoughts on this?

**Comment by justinbmeyer** [comment]
One thing I noticed is that there's no injection for `steal.production.js` or the `can/test/test.js` bundle.

**Comment by phillipskevin** [comment]
Are there any errors in the Firefox console?

**Comment by phillipskevin** [comment]
I was able to get this working locally by making these changes:

1. Roll back can-component to 3.0.3. The tests for 3.0.4 and above are failing on the latest firefox. See https://github.com/canjs/can-component/issues/75.

2. remove the todomvc Funcunit test

I'm not sure what changed to cause this to break, but it is throwing this error now:

```
TypeError: Error loading "can@3.3.0#test/test" at http://localhost:3996/dist/test/test.js
$(...).unload is not a function
Stack trace:
@http://localhost:3996/dist/bundles/can/test/test.js:74506:5
c/l.execute@http://localhost:3996/dist/node_modules/steal/steal.production.js:9:12843
```

I'll investigate this after fixing the can-component issue.
