### ISSUE TITLE
Documentation not building with bit-docs pre-release 0.0.8-0

### ISSUE THREAD

**Issue by leoj3n** [canjs/canjs#3575]
With `npm i bit-docs@latest --save-dev`:

```diff
diff --git a/package.json b/package.json
index 42df2641e..5c1111157 100644
--- a/package.json
+++ b/package.json
@@ -107,7 +107,7 @@
     "react-view-model": "0.5.6"
   },
   "devDependencies": {
-    "bit-docs": "^0.0.7",
+    "bit-docs": "0.0.8-0",
     "es6-promise": "^4.1.0",
     "feathers": "^2.0.3",
     "feathers-authentication-client": "^0.1.6",
```

Running `npm run document -- -d` errors with:

```
---snip---
npm http fetch GET 200 https://registry.npmjs.org/pkginfo 7ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/aws-sign 22ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/node-uuid 25ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/cookie-jar 27ms (from cache)
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm http fetch GET 200 https://registry.npmjs.org/options 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/pinkie-promise 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/pinkie 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/is-utf8 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/flexibility 56ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/can-control 59ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/steal-stache 46ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/jquery 60ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/can-util 69ms (from cache)
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/bit-docs/lunr.js.git
npm ERR!
npm ERR! fatal: Not a git repository: /Users/leoj/tmp/testbd/canjs/node_modules/bit-docs/../../../.git/modules/docs/modules/bit-docs
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leoj/.npm/_logs/2017-09-23T00_26_53_448Z-debug.log
/Users/leoj/tmp/testbd/canjs/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Cannot find module './node_modules/bit-docs-glob-finder/bit-docs'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /Users/leoj/tmp/testbd/canjs/node_modules/bit-docs/lib/configure/add-package-configuration.js:8:13
    at /Users/leoj/tmp/testbd/canjs/node_modules/lodash/lodash.js:3116:27
    at /Users/leoj/tmp/testbd/canjs/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/Users/leoj/tmp/testbd/canjs/node_modules/lodash/lodash.js:2654:24)
    at /Users/leoj/tmp/testbd/canjs/node_modules/lodash/lodash.js:4380:18
    at baseMap (/Users/leoj/tmp/testbd/canjs/node_modules/lodash/lodash.js:3115:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! can@3.10.3 document: `bit-docs "-d"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the can@3.10.3 document script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Looks like it's a possible issue with:

```
/usr/local/bin/git ls-remote -h -t ssh://git@github.com/bit-docs/lunr.js.git
```

Essentially, no `bit-docs.dependencies` are being installed to `canjs/node_modules/bit-docs/lib/configure/`.

I have tried [`bit-docs@0.0.8-0`](https://github.com/bit-docs/bit-docs/releases/tag/v0.0.8-0) with https://github.com/stealjs/stealjs and it works fine, so I think this issue is isolated to CanJS docs at this time. I also don't think it's something I changed. It looks like it's probably something to do with changes from @chasenlehara or @imaustink if I were to guess, unless there was a bad bit-docs merge (but I don't think there was b/c I looked and didn't find any).

**Comment by leoj3n** [comment]
Sorry @imaustink and @chasenlehara, I thought this issue was something with bit-docs search but now I actually think this might be due to some discrepancy of how the files are packaged by `npm publish`.

Using `bit-docs/bit-docs` or `file://...` to cloned master works fine to build the CanJS docs, but trying to use `0.0.8-0` from npm fails as above while `0.7.0` continues to work fine.

**Comment by leoj3n** [comment]
Looking at `bit-docs` files cloned from GitHub master to those from npm `.zip` there aren't any differences that I can see. No files added/removed/updated.

**Comment by leoj3n** [comment]
Seems to be an issue with using `npm publish` from a git submodule repo directory:

https://github.com/npm/npm/issues/18629

This happened because of how [`bit-docs-website` uses submodules](https://github.com/bit-docs/bit-docs-website/blob/master/.gitmodules), and I tried using `npm publish` from the `bit-docs` [submodule repo directory](https://github.com/bit-docs/bit-docs-website/tree/master/docs/modules).
