### ISSUE TITLE
'QueryLogic' is not exported by can@5.16.0#can

### ISSUE THREAD

**Issue by MarcGodard** [canjs/canjs#4579]
When developing this works: `import { DefineMap, DefineList, QueryLogic, connect } from 'can'`

But when I build, I get:
```
(node:9147) UnhandledPromiseRejectionWarning: Error: 'QueryLogic' is not exported by can@5.16.0#can
    at error (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:199:15)
```

Same with `connect`

**Comment by matthewp** [comment]
Could be a steal bug.

**Comment by matthewp** [comment]
@MarcGodard There was indeed a steal bug related to tree-shaking and the build that I fixed yesterday. If you could try updating to the latest steal version this might be fixed now.

**Comment by MarcGodard** [comment]
Still have the error using can@5.16.3

```
OPENING: base-site@0.0.0#components/modal-settings.component!done-component@2.2.0#component
(node:43810) UnhandledPromiseRejectionWarning: Error: 'QueryLogic' is not exported by can@5.16.3#can
    at error (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:199:15)
    at Module.error (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:16918:9)
    at handleMissingExport (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:17233:21)
    at /Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:19976:56
    at Array.reduce (<anonymous>)
    at Graph.handleMissingExport (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:19975:27)
    at Module.traceVariable (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:17007:28)
    at ModuleScope.findVariable (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:13445:29)
    at Identifier.bind (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:14129:40)
    at NewExpression.NodeBase.bind (/Users/marcgodard/GitHub/base-site/node_modules/steal-rollup/dist/rollup.js:13490:23)
```

**Comment by matthewp** [comment]
The bug was in steal, not canjs. Do you have steal `2.1.7`

**Comment by MarcGodard** [comment]
Yes, I updated all libs

    "steal": "^2.1.7",

**Comment by chasenlehara** [comment]
@MarcGodard Would you mind running `npm ls steal` in your project and pasting the results here please?

**Comment by matthewp** [comment]
I worked with Marc on this. This was fixed by a steal release.
